unaligned: "RAWDATA" # The hifi.bam file obtainied from the sequencer
analysis: "ANALYSIS" # folder where the git repo is cloned and analysis is performed
reference: "reference"
lib: "T-12U-16B" # UMI/Barcode designs
method: "knee" # Cell Calling Methods knne/percentile 
capture: "3prime" # 10X capture 3prime/5prime
sample: "samplename"
MAS_SMRTbell_adapters_barcodes: "resources/mas16_primers.fasta"
ref : "reference fasta file"
gtf: "annotation file (gtf)"
polya: "resources/mouse_and_human.polyA_motif.txt"
cagepeak: "resources/human.refTSS_v3.1.hg38.10X.chr.bed" # for human
p3: "resources/10X_Chromium_Single_Cell_3p_cDNA_Primers.fasta"
p5: "resources/10X_Chromium_Single_Cell_5p_cDNA_Primers.fasta"
whitelist_p3: "resources/3M-february-2018-REVERSE-COMPLEMENTED.txt.gz"
whitelist_p5: "resources/737K_august_2016.txt.gz"


#Cluster assign
large:
  mem: 400000
  runtime: 96:00:00
  partition: norm
medium:
  mem: 128000
  runtime: 1500
  partition: "norm"
small:
  mem: 32000
  runtime: 4:00:00
  partition: norm

